### ISSUE TITLE
Problem in seqlm tool

### ISSUE THREAD

**Issue by nitishkumarmishra** [raivokolde/seqlm#1]
Hi Raio,
I was looking for seqlm tools, I think this is the tool which was used in your research article "DNA methylome profiling of human tissues identifies global and tissue-specific methylation patterns". When I am using command which you provided in README file, I am getting this error-
data(tissue_small)
segments = seqlm(values = tissue_small$values, genome_information = tissue_small$genome_information, annotation =  tissue_small$annotation)

Error::
Error in seqlm_segmentation(values = values, genome_information = genome_information,  : 
could not find function "DataFrame"

Can you please suggest me how I can fix this problem.

Thanks
Nitish

**Comment by raivokolde** [comment]
There was a small bug introduced by changes in Bioconductor. Fixed it now. Thanks for noticing!

Best,
Raivo

**Comment by nitishkumarmishra** [comment]
Thanks
