### ISSUE TITLE
warning and error using seqlm

### ISSUE THREAD

**Issue by yzhang12** [raivokolde/seqlm#2]
When I load seqlm, a warning message shows up: replacing previous import ‘S4Vectors::Position’ by ‘ggplot2::Position’ when loading ‘seqlm’. I did some research online about this error. Some people suggest to update all packages so I did. But the problem didn't go away. So maybe there is a conflict between ggplot2 and S4Vectors? Some people suggest to use importFrom() selectively, or continue to declare Imports: in the DESCRIPTION file but use ggplot2::Position, etc., in the R code.

Another error I ran into is "Aesthetics must be either length 1 or the same as the data (1): xmin, xmax, ymin, ymax, group, x, y" when using seqlmreport.

**Comment by raivokolde** [comment]
Thanks for reporting. I can see the ggplot2::Position warning, but currently it does not seem to affect the results.

But can you elaborate more on how did you get the error. Maybe by including the a small reproducible example.

**Comment by yzhang12** [comment]
Thank you for replying. Here is a small dataset to reproduce the error. 

> test_betas=readRDS("test_betas.rds")
> test_anno=readRDS("test_anno.rds")
> test_seqlm_segs=seqlm(test_betas, genome_information = genome_information, annotation = test_anno)

[testfile.zip](https://github.com/raivokolde/seqlm/files/330560/testfile.zip)

Finding the best segmentation
  |==============================================================================================================================| 100%
Calculating coefficients and p-values for all regions
Adding additional information to the results
    All numeric variables
    Variable: UCSC_RefGene_Group
    Variable: Relation_to_UCSC_CpG_Island
    Variable: UCSC_RefGene_Name

> seqlmreport(test_seqlm_segs[1:20], test_betas, genome_information, test_anno, dir = "dmr/test_seqlm_results")
> Error: Aesthetics must be either length 1 or the same as the data (1): xmin, xmax, ymin, ymax, group, x, y
